### ISSUE TITLE
AlphaZeroでの教師データとしての報酬の与え方について

### ISSUE THREAD

**Issue by Michi-123** [horoiwa/deep_reinforcement_learning_gallery#18]

**Comment by Michi-123** [comment]
AlphaZeroの教師データ（セルフプレイでの生成データ） state, policy, reward について質問です。
AlphaZeroは、状態(state) から -> モデル(model.predict)で -> 次の手(policy) と現在の状態価値(value)を学習しますが、プログラムでは、セルフプレイの報酬 reward は、状態 state での player にとっての価値のように書かれています。
つまりこれは、その状態stateでのplayerにとって、方策policyが「勝ち」につながる場合は、reward は1、「負け」につながる場合はrewardは-1 になるように学習させているのでしょうか？

**Comment by horoiwa** [comment]
@Michi-123 
ご質問ありがとうございます

>その状態stateでのplayerにとって、方策policyが「勝ち」につながる場合は、reward は1、「負け」につながる場合はrewardは-1 になるように学習させているのでしょうか？

そのご理解で合っていそうな感じですが念のため何点か補足します。

#### 状態価値V(s_t)の訓練は最終的な勝ち負けを単純に教師あり学習

V(s)が学習しているのは手番プレイヤー視点での勝ち負けのみです。

1. ゲーム終了時に盤面s_t から最終的に勝利したならReward[s_t]=+1 敗北ならReward[s_t]=-1と教師ラベルを付けます
https://github.com/horoiwa/deep_reinforcement_learning_gallery/blob/8a9e329aa9aae0666c85679b9ae2fb3d40f02d49/AlphaZero/main.py#L77

2. 単純な教師あり学習でV(s) => 勝敗ラベル(1 or -1) を学習することで状態価値関数を訓練します
https://github.com/horoiwa/deep_reinforcement_learning_gallery/blob/8a9e329aa9aae0666c85679b9ae2fb3d40f02d49/AlphaZero/main.py#L214

よってV(s_t)の予測値が1に近いほど盤面s_tからゲームを続けて勝利したサンプルが多いということになります。

#### 報酬は方策policyに（それほど）依存しない

ややこしい話なのですがAlphaZeroのpolicyというのは一般的な強化学習用語としてのpolicyではなく、過去のMCTS試行の記憶にすぎません。そしてこのpolicyはMCTS試行回数を省エネ化するための事前信念（？）的な用途で使われます。すなわちMCTS試行回数が十分に大きければ方策policyはあっても無くても同じ行動選択（=>同じ勝敗=報酬ラベル）に収束するはずです。よって報酬はPolicyNetworkに概ね依存しないと理解できます。



疑問には答えられているでしょうか？

**Comment by Michi-123** [comment]
@horoiwa 様
　ありがとうございます。私の理解とすり合わせてみてコード通りであることを確認できました。ありがとうございました。また「報酬は方策policyに（それほど）依存しない」という部分は、なるほどと思いました。
　max(Q + U) についても考えてみたいと思います。

**Comment by horoiwa** [comment]
@Michi-123 さん

>max(Q + U) について

t時に状態sにあり行動aをとったときの状態行動価値 Q（st, at）は

- Q(st, at) = R(s_{t+1}) + (1-done) * V(s_{t+1}})

ここで、
- done = 1 if t+1時にゲーム終了 else 0
- 囲碁は即時報酬がないのでR(s_t)はゲーム終了時以外は0であることに注意


一人用ゲームならこれでいいのですが、囲碁のような二人用ゲームだと、R(s_{t+1}) も V(s_{t+1}}) も相手視点での評価になるのでこのままだと相手にとってもっとも都合がよい行動が状態行動価値最大になってしまいます。

そこで、二人用ゲームでは符号を反転させることで相手にとってもっとも都合が悪い行動が自分視点での状態行動価値が最大になるようにします。

- Q(st, at) = **-1** × ( R(s_{t+1}) + (1-done) * V(s_{t+1}}) )


https://github.com/horoiwa/deep_reinforcement_learning_gallery/blob/8a9e329aa9aae0666c85679b9ae2fb3d40f02d49/AlphaZero/mcts.py#L75


なので例えば、t時において状態sにあるとき行動aを選択すrとt+1時において相手の勝利でゲーム終了するならば

Q(s_t, a_t) = -1 × ( 1 + (1 - 1)  * V(s_{t+1}} ) = -1

となり、相手の勝利につながる行動の価値が低くなります。

**Comment by Michi-123** [comment]
納得できました。一人ゲームの場合の例や、時刻tでの厳密な表現もSuttonの教科書のようで大変分かりやすかったです。ありがとうございました。
